feat: Adding support for Kustomize projects

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,6 +13,7 @@ on:
 env:
   HELM_DOCS_VERSION: "1.14.2"    
   HELM_DOCS_PLATFORM: "Linux_x86_64"
+  KUSTOMIZE_VERSION: "5.0.4"
 
 jobs:
   test-typescript:
@@ -61,6 +62,9 @@ jobs:
       - id: helm-chart-listing
         uses: "./.github/actions/helm-chart/listing"
 
+      - id: kustomize-listing
+        uses: "./.github/actions/kustomize/listing"
+
       - id: helm-chart-build-dependencies
         uses: "./.github/actions/helm-chart/dep-build"
 
@@ -69,6 +73,9 @@ jobs:
       
       - id: helm-chart-manifest-validation
         uses: "./.github/actions/helm-chart/manifest-validation"
+
+      - id: kustomize-manifest-validation
+        uses: "./.github/actions/kustomize/manifest-validation"
       
       - id: helm-chart-version-bump
         uses: "./.github/actions/helm-chart/version-bump"
@@ -100,6 +107,31 @@ jobs:
           echo "$DEST" >>$GITHUB_PATH
           echo $PWD
           $PWD/helm-docs --version          
+          ############################################################
+
+      - name: install-kustomize        
+        shell: bash        
+        run: |
+          set -euo pipefail
+          ############################################################
+          DEST="$RUNNER_TEMP/kustomize"
+          echo "Downloading Kustomize..."
+          mkdir -p "$DEST"
+          cd "$DEST"
+
+          if ! curl -sLO "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${{ env.KUSTOMIZE_VERSION}}/kustomize_v${{ env.KUSTOMIZE_VERSION}}_linux_amd64.tar.gz"; then
+            echo "!!! ERROR downloading Kustomize v${{ env.KUSTOMIZE_VERSION}} !!!"
+            exit 1
+          fi
+
+          if ! tar -xzf "kustomize_v${{ env.KUSTOMIZE_VERSION}}_linux_amd64.tar.gz" kustomize; then
+            echo "!!! ERROR unpacking kustomize_v${{ env.KUSTOMIZE_VERSION}}_linux_amd64.tar.gz !!!"
+            exit 1
+          fi
+          ls -al
+          echo "$DEST" >>$GITHUB_PATH
+          echo $PWD
+          $PWD/kustomize version          
           ############################################################
         
       - id: helm-chart-docs
diff --git a/.github/workflows/git-pr-status-checks.yml b/.github/workflows/git-pr-status-checks.yml
--- a/.github/workflows/git-pr-status-checks.yml
+++ b/.github/workflows/git-pr-status-checks.yml
@@ -38,6 +38,7 @@ concurrency:
 env:
   HELM_DOCS_VERSION: "1.14.2"    
   HELM_DOCS_PLATFORM: "Linux_x86_64"
+  KUSTOMIZE_VERSION: "5.0.4"
 
 jobs:
   pr-status-check:
@@ -57,6 +58,9 @@ jobs:
             
       - id: helm-chart-listing
         uses: "openmcp-project/blueprint-workflows/.github/actions/helm-chart/listing@feat/kustomize"
+
+      - id: kustomize-listing
+        uses: "openmcp-project/blueprint-workflows/.github/actions/kustomize/listing@feat/kustomize"
 
       # Workflow supports only one helm repo add for now. If you need to add multiple helm repos, you need to copy and modify this workflow.
       - id: helm-repo-add
@@ -97,6 +101,9 @@ jobs:
       - id: helm-chart-manifest-validation
         uses: "openmcp-project/blueprint-workflows/.github/actions/helm-chart/manifest-validation@feat/kustomize"
 
+      - id: kustomize-manifest-validation
+        uses: "openmcp-project/blueprint-workflows/.github/actions/kustomize/manifest-validation@feat/kustomize"
+
       - id: helm-chart-version-bump
         uses: "openmcp-project/blueprint-workflows/.github/actions/helm-chart/version-bump@feat/kustomize"
         with:
@@ -128,6 +135,31 @@ jobs:
           echo $PWD
           $PWD/helm-docs --version          
           ############################################################
+
+      # - name: install-kustomize        
+      #   shell: bash        
+      #   run: |
+      #     set -euo pipefail
+      #     ############################################################
+      #     DEST="$RUNNER_TEMP/kustomize"
+      #     echo "Downloading Kustomize..."
+      #     mkdir -p "$DEST"
+      #     cd "$DEST"
+
+      #     if ! curl -sLO "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${{ env.KUSTOMIZE_VERSION}}/kustomize_v${{ env.KUSTOMIZE_VERSION}}_linux_amd64.tar.gz"; then
+      #       echo "!!! ERROR downloading Kustomize v${{ env.KUSTOMIZE_VERSION}} !!!"
+      #       exit 1
+      #     fi
+
+      #     if ! tar -xzf "kustomize_v${{ env.KUSTOMIZE_VERSION}}_linux_amd64.tar.gz" kustomize; then
+      #       echo "!!! ERROR unpacking kustomize_v${{ env.KUSTOMIZE_VERSION}}_linux_amd64.tar.gz !!!"
+      #       exit 1
+      #     fi
+      #     ls -al
+      #     echo "$DEST" >>$GITHUB_PATH
+      #     echo $PWD
+      #     $PWD/kustomize version          
+      #     ############################################################
         
       - id: helm-chart-docs
         uses: "openmcp-project/blueprint-workflows/.github/actions/helm-chart/docs@feat/kustomize"
